import numpy as np

osim_joints_name_dict = {
 0: 'pelvis',
 1: 'femur_r',
 2: 'tibia_r',
 3: 'talus_r',
 4: 'calcn_r',
 5: 'toes_r',
 6: 'femur_l',
 7: 'tibia_l',
 8: 'talus_l',
 9: 'calcn_l',
 10: 'toes_l',
 11: 'lumbar_body',
 12: 'thorax',
 13: 'head',
 14: 'scapula_r',
 15: 'humerus_r',
 16: 'ulna_r',
 17: 'radius_r',
 18: 'hand_r',
 19: 'scapula_l',
 20: 'humerus_l',
 21: 'ulna_l',
 22: 'radius_l',
 23: 'hand_l'}


osim2smpl_corresp = {
'pelvis' : ['Pelvis'],
'femur_r' :['R_Hip'],
'tibia_r' :['R_Knee'],
'talus_r' : ['R_Ankle'],
'calcn_r' : ['R_Ankle'],
'toes_r' : ['R_Foot'],
'femur_l' : ['L_Hip'],
'tibia_l' : ['L_Knee'],
'talus_l' : ['L_Ankle'],
'calcn_l' : ['L_Ankle'],
'toes_l' : ['L_Foot'],
'lumbar_body' : ['Pelvis'],
'thorax' : ['Spine1','Spine2', 'Spine3'],
'head' : ['Head','Neck', ],
'scapula_r' : ['R_Collar'],
'humerus_r' : ['R_Shoulder'],
'ulna_r' : ['R_Elbow'],
'radius_r' : ['R_Elbow'],
'hand_r' : ['R_Wrist'],
'scapula_l' : ['L_Collar'],
'humerus_l' : ['L_Shoulder'],
'ulna_l' : ['L_Elbow'],
'radius_l' : ['L_Elbow'],
'hand_l' : ['L_Wrist']}


smpl2osim_corresp = {
 'Pelvis':   ['pelvis'],
 'L_Hip':    ['femur_l'],
 'R_Hip':    ['femur_r'],
 'Spine1':   ['lumbar_body'],
 'L_Knee':   ['tibia_l'],
 'R_Knee':   ['tibia_r'],
 'Spine2':   ['thorax'],
 'L_Ankle':  ['talus_l', 'calcn_l'],
 'R_Ankle':  ['talus_r', 'calcn_r'],
 'Spine3':   ['thorax'],
 'L_Foot':   ['toes_l'],
 'R_Foot':   ['toes_r'],
 'Neck':     ['head'],
 'L_Collar': ['scapula_l'],
 'R_Collar': ['scapula_r'],
 'Head':     ['head'], 
 'L_Shoulder':   ['humerus_l'],
 'R_Shoulder':   ['humerus_r'],
 'L_Elbow':  ['ulna_l', 'radius_l'],
 'R_Elbow':  ['ulna_r', 'radius_r'],
 'L_Wrist':  ['hand_l'],
 'R_Wrist':  ['hand_r'],
 'L_Hand':   ['hand_l'],
 'R_Hand':   ['hand_r'],
 }

osim2smpl_params_corresp = {
#  0: 'pelvis_tilt',
#  1: 'pelvis_list',
#  2: 'pelvis_rotation',
#  3: 'pelvis_tx',
#  4: 'pelvis_ty',
#  5: 'pelvis_tz',
6: [2*3+0], #'hip_flexion_r',
7: [2*3+2],#  7: 'hip_adduction_r',
#  8: 'hip_rotation_r',
9: [5*3], #'knee_angle_r',
#  10: 'ankle_angle_r',
#  11: 'subtalar_angle_r',
#  12: 'mtp_angle_r',
13: [-1*3+0], #'hip_flexion_l',
# 14 : [1*3+0, 1*3+1, 1*3+2],#  14: 'hip_adduction_l',
#  15: 'hip_rotation_l',
16 : [4*3+0],#'knee_angle_l',
#  17: 'ankle_angle_l',
#  18: 'subtalar_angle_l',
#  19: 'mtp_angle_l',
#  20: 'lumbar_bending',
#  21: 'lumbar_extension',
#  22: 'lumbar_twist',
#  23: 'thorax_bending',
#  24: 'thorax_extension',
#  25: 'thorax_twist',
#  26: 'head_bending',
#  27: 'head_extension',
#  28: 'head_twist',
#  29: 'scapula_abduction_r',
#  30: 'scapula_elevation_r',
#  31: 'scapula_upward_rot_r',
#  32: 'shoulder_r_x',
#  33: 'shoulder_r_y',
#  34: 'shoulder_r_z',
#  35: 'elbow_flexion_r',
#  36: [19*3+0, 19*3+1, 19*3+2, 21*3+0, 21*3+1, 21*3+2], # 'pro_sup_r',
#  37: 'wrist_flexion_r',
#  38: 'wrist_deviation_r',
#  39: 'scapula_abduction_l',
#  40: 'scapula_elevation_l',
#  41: 'scapula_upward_rot_l',
#  42: 'shoulder_l_x',
#  43: 'shoulder_l_y',
#  44: 'shoulder_l_z',
#  45: 'elbow_flexion_l',
#  46: 'pro_sup_l',
#  47: 'wrist_flexion_l',
#  48: 'wrist_deviation_l'
}
    
osim_params_to_smpl_joint ={ # For each param of osim, list the corresponding smpl limb as joints index
 0: [0], #'pelvis_tilt',
 1: [0], #'pelvis_list',
 2: [0], #'pelvis_rotation',
#  3: [0]'pelvis_tx',
#  4: [0]'pelvis_ty',
#  5: [0]'pelvis_tz',
 6: [2], #'hip_flexion_r',
 7: [2], #'hip_adduction_r',
 8: [2], #'hip_rotation_r',
 9: [5], #'knee_angle_r',
 10: [8], #'ankle_angle_r',
 11: [8], #'subtalar_angle_r',
 12: [11], #'mtp_angle_r',
 13: [8], #'hip_flexion_l',
#  14: 'hip_adduction_l',
#  15: 'hip_rotation_l',
#  16: 'knee_angle_l',
#  17: 'ankle_angle_l',
#  18: 'subtalar_angle_l',
#  19: 'mtp_angle_l',
#  20: 'lumbar_bending',
#  21: 'lumbar_extension',
#  22: 'lumbar_twist',
#  23: 'thorax_bending',
#  24: 'thorax_extension',
#  25: 'thorax_twist',
#  26: 'head_bending',
#  27: 'head_extension',
#  28: 'head_twist',
#  29: 'scapula_abduction_r',
#  30: 'scapula_elevation_r',
#  31: 'scapula_upward_rot_r',
#  32: 'shoulder_r_x',
#  33: 'shoulder_r_y',
#  34: 'shoulder_r_z',
#  35: 'elbow_flexion_r',
#  36: 'pro_sup_r',
#  37: 'wrist_flexion_r',
#  38: 'wrist_deviation_r',
#  39: 'scapula_abduction_l',
#  40: 'scapula_elevation_l',
#  41: 'scapula_upward_rot_l',
#  42: 'shoulder_l_x',
#  43: 'shoulder_l_y',
#  44: 'shoulder_l_z',
#  45: 'elbow_flexion_l',
#  46: 'pro_sup_l',
#  47: 'wrist_flexion_l',
#  48: 'wrist_deviation_l'}   
}

osim_params_name_dict = {
 0: 'pelvis_tilt',
 1: 'pelvis_list',
 2: 'pelvis_rotation',
 3: 'pelvis_tx',
 4: 'pelvis_ty',
 5: 'pelvis_tz',
 6: 'hip_flexion_r',
 7: 'hip_adduction_r',
 8: 'hip_rotation_r',
 9: 'knee_angle_r',
 10: 'ankle_angle_r',
 11: 'subtalar_angle_r',
 12: 'mtp_angle_r',
 13: 'hip_flexion_l',
 14: 'hip_adduction_l',
 15: 'hip_rotation_l',
 16: 'knee_angle_l',
 17: 'ankle_angle_l',
 18: 'subtalar_angle_l',
 19: 'mtp_angle_l',
 20: 'lumbar_bending',
 21: 'lumbar_extension',
 22: 'lumbar_twist',
 23: 'thorax_bending',
 24: 'thorax_extension',
 25: 'thorax_twist',
 26: 'head_bending',
 27: 'head_extension',
 28: 'head_twist',
 29: 'scapula_abduction_r',
 30: 'scapula_elevation_r',
 31: 'scapula_upward_rot_r',
 32: 'shoulder_r_x',
 33: 'shoulder_r_y',
 34: 'shoulder_r_z',
 35: 'elbow_flexion_r',
 36: 'pro_sup_r',
 37: 'wrist_flexion_r',
 38: 'wrist_deviation_r',
 39: 'scapula_abduction_l',
 40: 'scapula_elevation_l',
 41: 'scapula_upward_rot_l',
 42: 'shoulder_l_x',
 43: 'shoulder_l_y',
 44: 'shoulder_l_z',
 45: 'elbow_flexion_l',
 46: 'pro_sup_l',
 47: 'wrist_flexion_l',
 48: 'wrist_deviation_l'}

osim_kintree_table = np.array([
[4294967295, 0],
[0, 1],
[1,2],
[2,3],
[3,4],
[4,5],
[0,6],
[6,7],
[7,8],
[8,9],
[9,10],
[0,11],
[11,12],
[12,13],
[12,14],
[14,15],
[15,16],
[16,17],
[17,18],
[12,19],
[19,20],
[20,21],
[21,22],
[22,23],
]).T



osim_joints_rigged_to_smpl_joints = [
 [0, 0],  #'pelvis',
 [1, 2],  #'femur_r',
 [2, 5],  #'tibia_r',
 [3, 8],  #'talus_r',
 [4, 8],  #'calcn_r',
 [5, 11], #'toes_r',
 [6, 1], #'femur_l',
 [7, 4],  #'tibia_l',
 [8, 7], #'talus_l',
 [9, 7], #'calcn_l',
 [10, 10], #'toes_l',
 [11, 3],  #'lumbar_body',
 [12, 6], #'thorax',
 [13, 15], #'head',
 [14, 14], #'scapula_r',
 [15, 17], #'humerus_r',
 [16, 19],  #'ulna_r',
 [17, 19],  #'radius_r',
 [18, 21], #'hand_r',
 [19, 13], #'scapula_l',
 [20, 16], #'humerus_l',
 [21, 18], #'ulna_l',
 [22, 18], #'radius_l',
 [23, 20]]#'hand_l']